# Generated by Django 4.2.4 on 2024-11-10 11:29

import core.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(default=core.models.generate_unique_id, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='current_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('member', 'member'), ('professional_associate', 'professional_associate'), ('admin', 'admin')], default='member', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_profile',
            field=models.CharField(choices=[('advanced_associate', 'Advanced Associate'), ('normal_associate', 'Normal Associate'), ('super_admin', 'Super Admin'), ('content_manager', 'Content Manager'), ('gset_member', 'GSET Member')], default='gset_member', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='account',
            name='region_of_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
    ]
