# Generated by Django 4.2.4 on 2024-11-10 11:33

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_region_account_current_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(default=core.models.generate_unique_id, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=5, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district', to='core.region')),
            ],
            options={
                'db_table': 'district',
            },
        ),
    ]
