# Generated by Django 4.2.4 on 2024-11-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_region_code_region_enabled_alter_region_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='professional_associations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='short_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
