# Generated by Django 4.2.4 on 2024-11-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_account_linkedin_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
