# Generated by Django 4.2.4 on 2024-11-10 17:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.CharField(default=core.models.generate_unique_id, editable=False, max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='course_contents')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
