# Generated by Django 4.2.4 on 2024-11-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_adminuser_email_adminuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
