# Generated by Django 4.2.4 on 2024-11-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_adminuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='membership_type',
            field=models.CharField(choices=[('student', 'Student'), ('professional_teacher', 'Professional Teacher')], default='professional_teacher', max_length=25, null=True),
        ),
    ]
