# Generated by Django 4.2.4 on 2024-11-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_job_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
